# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0blinguaboost\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"A\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\noperations\x18\x03 \x03(\t\"\xee\x01\n\x0cTextResponse\x12\x16\n\x0eprocessed_text\x18\x01 \x01(\t\x12\x19\n\x11original_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\x12\x39\n\x08metadata\x18\x04 \x03(\x0b\x32\'.linguaboost.TextResponse.MetadataEntry\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\rStatusRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"w\n\x0eStatusResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x12\x1a\n\x12processed_requests\x18\x04 \x01(\x05\x12\x0f\n\x07version\x18\x05 \x01(\t2\xde\x01\n\x0c\x41gentService\x12@\n\x08SayHello\x12\x19.linguaboost.HelloRequest\x1a\x17.linguaboost.HelloReply\"\x00\x12\x44\n\x0bProcessText\x12\x18.linguaboost.TextRequest\x1a\x19.linguaboost.TextResponse\"\x00\x12\x46\n\tGetStatus\x12\x1a.linguaboost.StatusRequest\x1a\x1b.linguaboost.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=56
  _globals['_HELLOREPLY']._serialized_start=58
  _globals['_HELLOREPLY']._serialized_end=87
  _globals['_TEXTREQUEST']._serialized_start=89
  _globals['_TEXTREQUEST']._serialized_end=154
  _globals['_TEXTRESPONSE']._serialized_start=157
  _globals['_TEXTRESPONSE']._serialized_end=395
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_start=348
  _globals['_TEXTRESPONSE_METADATAENTRY']._serialized_end=395
  _globals['_STATUSREQUEST']._serialized_start=397
  _globals['_STATUSREQUEST']._serialized_end=430
  _globals['_STATUSRESPONSE']._serialized_start=432
  _globals['_STATUSRESPONSE']._serialized_end=551
  _globals['_AGENTSERVICE']._serialized_start=554
  _globals['_AGENTSERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
